language: node_js
node_js:
  - stable
install:
  - npm i
  - npm i element-theme -g
script:
  - et -o src/style/theme/
  - npm run build
after_success:
  - tar cvzf yasa-$TRAVIS_TAG.tgz dist/*
deploy:
  provider: releases
  api_key:
    secure: SQ8j0GHKKARv4JnF9+1/QysklJL4JnJfnJkgAhGfqSgIjHWa1f8Z/1QTNal3raiRErvyE1s+cEWr63iIGdA8ab7QvlekSiyRt6t852JFozhbAHkQn4R/R9E/hHcqg1VQx49HGA932dYeDStNU+HSJpWikI1g1XM5RZpTERs8u+wK5P+rcyyEslrCZzYXQz6O5TpC0VJUzNkdisNFliUVFmtEenXY3nTqtXgi0oBfqE9kN50GNyg1iHmJIA6vwt5Gom0YtfKEpbW4Jx0z0qYnpwugaWweYJzN11itYaf69yx64oM1kYgZIlWI9HRSeFX3QcJ2l0jNyij02ixRvtZZFpa4HEWGULyL76199dusPRvcL//8o40AAHC07P8UET8elt+XqkE/eYopJUZsdvGSIqUrMMn2iRIT8YgAviS2BA5GZY622rkgxy7uus3K8wogpYFNZZSxwWlFmpZ+j3lR+tnbR/JJKn9o/LeuSB3WZfmySzfgF5XDGH81r8ik6EI67v7zezubdELQjolYNHeBo1BeFCgBVrl1BW2nIp+QMHqdz/WGasgB9r6lMlsYVX5Xssxq/edjRnaFAJIrLvyDlJY1UYNH3wZ9PD3fBldZPO1By25oaTA+x54AFsP/IUzuG4OHWGEXTJrCzD6G85DT3lUp/2Xf+UoY6dIswHV+P4s=
  file: yasa-$TRAVIS_TAG.tgz
  skip_cleanup: true
  on:
    repo: kezhenxu94/yasa
    tags: true
